version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-44-209-158-64.compute-1.amazonaws.com
            port: '5432'
            database: d6ug9tm1vga4jv
            schema: schema-graphql
            user: zzakmcsvfktbbp
            password: aba5fb76047c154482f13204895074c3148986ee700f264ab3dc6c9f1ffeea24
            migrations: true